# Form implementation generated from reading ui file 'currencydesign.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(646, 397)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Betrag = QtWidgets.QDoubleSpinBox(parent=self.centralwidget)
        self.Betrag.setGeometry(QtCore.QRect(80, 10, 62, 22))
        self.Betrag.setObjectName("Betrag")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 61, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 10, 101, 21))
        self.label_2.setObjectName("label_2")
        self.Waehrung = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Waehrung.setGeometry(QtCore.QRect(290, 10, 113, 21))
        self.Waehrung.setObjectName("Waehrung")
        self.ausgabefeld = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.ausgabefeld.setGeometry(QtCore.QRect(3, 70, 641, 211))
        self.ausgabefeld.setObjectName("ausgabefeld")
        self.calculateButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.calculateButton.setGeometry(QtCore.QRect(480, 10, 91, 31))
        self.calculateButton.setObjectName("calculateButton")
        self.exitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(84, 310, 171, 31))
        self.exitButton.setObjectName("exitButton")
        self.resetButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(370, 320, 141, 24))
        self.resetButton.setObjectName("resetButton")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(190, 40, 101, 21))
        self.label_3.setObjectName("label_3")
        self.zielWaehrung = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.zielWaehrung.setGeometry(QtCore.QRect(290, 40, 113, 21))
        self.zielWaehrung.setObjectName("zielWaehrung")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 646, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CurrencyConverter"))
        self.label.setText(_translate("MainWindow", "Betrag:"))
        self.label_2.setText(_translate("MainWindow", "Base-Währung:"))
        self.calculateButton.setText(_translate("MainWindow", "Umrechnen"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.resetButton.setText(_translate("MainWindow", "Zurücksetzen"))
        self.label_3.setText(_translate("MainWindow", "Ziel-Währung:"))
